#!/usr/bin/env python3
"""
CAL (Contract Assertion Layer) — 基于 seam-agreement.md 中的 @ptg 注解生成 pytest 断言脚本。

用法:
    python scripts/ptg-cal-gen.py --input docs/seam-agreement.md --output tests/test_contract_assertions.py

注解格式:
    @ptg: type=str, nullable=false, required=true, enum=[A,B,C], pattern=/^[a-z]+$/

输出: 自动生成对应字段的 pytest 断言函数，写入 tests/ 目录。
      这些断言在 PTG（物理测试环境）执行时同步运行。
"""

import argparse
import re
import sys


ANNOTATION_RE = re.compile(r'@ptg:\s*(.*)')
FIELD_RE = re.compile(r'^[-*]\s+(\w[\w\-]*)\s*:', re.MULTILINE)


def parse_fields(md_text):
    """从 Markdown 中提取字段及其 @ptg 注解。"""
    fields = []
    lines = md_text.split('\n')
    current_field = None

    for line in lines:
        field_match = FIELD_RE.match(line.strip())
        if field_match:
            if current_field:
                fields.append(current_field)
            current_field = {'name': field_match.group(1), 'ptg': {}}

        ptg_match = ANNOTATION_RE.search(line)
        if ptg_match and current_field:
            raw = ptg_match.group(1)
            # 先提取 enum=[...] 整体避免逗号拆分破坏内容
            enum_blocks = []
            def replace_enum(m):
                idx = len(enum_blocks)
                enum_blocks.append(m.group(0))
                return f'__ENUM_BLOCK_{idx}__'
            clean = re.sub(r'\[([^\]\[,]+\b(?:,\s*\b[^\]\[,]+)+)\]', replace_enum, raw)
            pairs = clean.split(',')
            for pair in pairs:
                pair = pair.strip()
                if '=' not in pair:
                    continue
                k, v = pair.split('=', 1)
                key = k.strip()
                val = v.strip()
                # 还原 enum 块
                for i, block in enumerate(enum_blocks):
                    val = val.replace(f'__ENUM_BLOCK_{i}__', block)
                # 类型转换
                if val.startswith('[') and val.endswith(']'):
                    inner = val[1:-1]
                    val = [x.strip().strip('"').strip("'") for x in inner.split(',')]
                elif val.lower() == 'true':
                    val = True
                elif val.lower() == 'false':
                    val = False
                else:
                    try:
                        val = int(val)
                    except ValueError:
                        pass
                current_field['ptg'][key] = val

    if current_field:
        fields.append(current_field)

    return fields


def generate_assertions(fields):
    """将 @ptg 注解转换为 pytest 断言代码。"""
    out = []
    out.append('"""\nAuto-generated by ptg-cal-gen.py. Do not edit manually.\n"""\n')
    out.append('import pytest\nimport re\n\n')

    type_map = {'str': 'str', 'string': 'str', 'int': 'int', 'integer': 'int',
                'float': 'float', 'bool': 'bool', 'boolean': 'bool'}

    for field in fields:
        name = field['name']
        safe_name = name.replace('-', '_')
        ptg = field['ptg']

        # required 检查
        if ptg.get('required') is True:
            out.append(f'def test_{safe_name}_must_not_be_none():\n')
            out.append(f'    assert {name} is not None, "{name} is required"\n\n')

        # nullable 检查
        if ptg.get('nullable') is False:
            out.append(f'def test_{safe_name}_rejects_null():\n')
            out.append(f'    with pytest.raises((AssertionError, TypeError)):\n')
            out.append(f'        validate_nullable({name}, nullable=False)\n\n')

        # type 检查
        if 'type' in ptg:
            py_type = type_map.get(str(ptg['type']), ptg['type'])
            out.append(f'def test_{safe_name}_type_check():\n')
            out.append(f'    assert isinstance({name}, {py_type}), f"{{ {name} }} expected {{ {py_type} }}"')

            # pattern 检查
            if 'pattern' in ptg:
                regex = str(ptg['pattern']).strip('/')
                out.append(f'    assert re.match(r"{regex}", str({name})), "pattern mismatch"\n')
            out.append('\n')

        # enum 检查
        if 'enum' in ptg and isinstance(ptg['enum'], list):
            vals = ', '.join([f'"{v}"' for v in ptg['enum']])
            out.append(f'def test_{safe_name}_enum_check():\n')
            out.append(f'    assert {name} in [{vals}], f"{{ {name} }} not in {{{{{vals}}}}}"\n\n')

    return '\n'.join(out)


def main():
    parser = argparse.ArgumentParser(description='Generate pytest assertions from @ptg annotations.')
    parser.add_argument('--input', '-i', required=True, help='seam-agreement.md path')
    parser.add_argument('--output', '-o', required=True, help='Output test file path')
    args = parser.parse_args()

    with open(args.input, 'r') as f:
        md_text = f.read()

    fields = parse_fields(md_text)
    assertions = generate_assertions(fields)

    with open(args.output, 'w') as f:
        f.write(assertions)

    print(f"Generated {len(fields)} assertion functions -> {args.output}")


if __name__ == '__main__':
    main()
